
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-hub
    ports:
      - "5673:5672"
      - "15673:15672"
    networks:
      - rede-geral
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  api:
    build: .
    env_file:
      - .env
    environment:
      BROKER_URL: amqp://rabbitmq:5672
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "3031:3031"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - rede-geral
networks:
  rede-geral:
    external: true