
services:
  api:
    build: .
    # O Compose lê o arquivo local e entrega as chaves para o SO do container
    env_file:
      - .env 
    ports:
      - "3000:3000"
    networks:
      - rede-geral
networks:
  rede-geral:
    external: true