export type ProductType = {
    codigo: number;
    id: string;
    estoque: number;
    preco: string;
    unidade_medida: string;
    grupo: number;
    origem: string;
    descricao: string;
    num_fabricante: string;
    num_original: string;
    sku: string;
    marca: number;
    ativo: string;
    class_fiscal: string;
    cst: string;
    tipo: number;
    caracteristica: number;
    data_cadastro: string;
    data_recadastro: string;
    observacoes1: string;
    observacoes2: string;
    observacoes3: string;
};
